Update .local/bin/update_chezmoi

diff --git a/home/dot_local/bin/executable_update_chezmoi b/home/dot_local/bin/executable_update_chezmoi
--- a/home/dot_local/bin/executable_update_chezmoi
+++ b/home/dot_local/bin/executable_update_chezmoi
@@ -1,11 +1,31 @@
 #!/usr/bin/env bash
 
-command -v dpkg > /dev/null 2>&1 || { echo "Error: This program is for Debian/Ubuntu" >&2 ; exit 1 ; }
+ARCH=$(dpkg --print-architecture 2> /dev/null)
+SYSTEM=$(uname -s | tr '[:upper:]' '[:lower:]')
+repo=twpayne/chezmoi
+search="_${SYSTEM:-linux}_${ARCH:-amd64}[.]"
 
-ARCH=$(dpkg --print-architecture)
+test_mode=false
+[[ "$1" == "-t" ]] && test_mode=true
+
+if ! $test_mode; then
+  command -v dpkg > /dev/null 2>&1 || { echo "Error: This program is for Debian/Ubuntu" >&2 ; exit 1 ; }
+fi
+
 # Get download url
 url=$(curl -s https://api.github.com/repos/twpayne/chezmoi/releases/latest | \
-  awk -F'"' -va="$ARCH" '$0 ~ "\"browser_download_url\": \".*/chezmoi_.*_linux_"a"\\.deb\""{print $4}')
+  awk -F'"' -v search="$search" '
+      $4 ~ search &&
+      /^[[:space:]]*"browser_download_url":/ &&
+      /\.deb"$/ {
+      print $4
+    }
+  ')
+
+if $test_mode; then
+  echo url=$url
+  exit
+fi
 
 if [[ -z "$url" ]]; then
   echo "Error: Could not determine download url" >&2
