I've switched to xscreensaver, so several scripts had to be updated. I also switched to NeoVim, so I made my my config work with both. ~/.config/nvim/init.vim is a symlink to ~/.vimrc Other fixes and cleanup

diff --git a/bin/term b/bin/term
--- a/bin/term
+++ b/bin/term
@@ -1,12 +1,18 @@
 #!/bin/sh
 
-[ $1 ] && { which $1 > /dev/null 2>&1 && { { $1 & } && exit; } || { echo "Warning: $1 not found">/dev/stderr; }; }
+if [ "$1" = "-T" ] && [ $2 ]; then
+  if which $2 > /dev/null 2>&1; then
+    term=$2
+    shift 2
+    { { $term $* & } && exit; } || { echo "Warning: $1 not found">/dev/stderr; };
+  fi
+fi
 
 for term in kitty alacritty st urxvtc urxvt xfce4-terminal gnome-terminal xterm; do
   if [ $term = urxvtc ]; then
-    which urxvtc > /dev/null 2>&1 && pgrep -u $LOGNAME -x urxvtd && { urxvtc & } && exit
+    which urxvtc > /dev/null 2>&1 && pgrep -u $LOGNAME -x urxvtd && { urxvtc $* & } && exit
   else
-    which $term > /dev/null 2>&1 && { $term & } && exit
+    which $term > /dev/null 2>&1 && { $term $* & } && exit
   fi
 done
 
