Update .bashrc

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -59,81 +59,73 @@ __prompt_trim_pwd() {
 # Load git prompt
 [ -r "$XDG_CONFIG_HOME"/shell/git-prompt ] && . "$XDG_CONFIG_HOME"/shell/git-prompt
 
-# Set the prompt for bash
-if [[ -n "$BASH_VERSION" ]]; then
-  # \1 & \2 are good for the vi-ins-mode-string but \[ and \] are good for PS1
-  # Colors: black:30, red:31, green:32, yellow:33, blue:34, magenta:35, cyan:36, white:37
-  # foreground:38, background:48, reset_foreground:39, reset_background:49
-  # bright_foreground:+60, bright_background:+70
-  # bold:1, unbold:22, underline:4, un-underline:24, reverse:7, unreverse:27
-  # orange:38;2;255;165;0 (a little darker: 38;5;208
+# Set the prompt
+# \1 & \2 are good for the vi-ins-mode-string but \[ and \] are good for PS1
+# Colors: black:30, red:31, green:32, yellow:33, blue:34, magenta:35, cyan:36, white:37
+# foreground:38, background:48, reset_foreground:39, reset_background:49
+# bright_foreground:+60, bright_background:+70
+# bold:1, unbold:22, underline:4, un-underline:24, reverse:7, unreverse:27
+# orange:38;2;255;165;0 (a little darker: 38;5;208
 
-  # Set up a good looking orange
-  __orange='0;33'
-  [[ "$TERM" != linux && "$TERM" != vt220 ]] && __orange='38;5;208'
+# Set up a good looking orange
+__orange='0;33'
+[[ "$TERM" != linux && "$TERM" != vt220 ]] && __orange='38;5;208'
 
-  PROMPT_DIRTRIM=2
-  shopt -s autocd cdspell extglob histappend
+PROMPT_DIRTRIM=2
+shopt -s autocd cdspell extglob histappend
 
-  # Show the mode in the prompt
-  bind 'set show-mode-in-prompt on'
+# Show the mode in the prompt
+bind 'set show-mode-in-prompt on'
 
-  # Lower the timeout for pressing escape
-  bind 'set keyseq-timeout 100'
+# Lower the timeout for pressing escape
+bind 'set keyseq-timeout 100'
 
-  # Set emacs-mode and vi-ins-mode to reset codes
-  bind "set emacs-mode-string \"\1\e[1m\2\""
-  bind "set vi-ins-mode-string \"\1\e[1m\2\""
+# Set emacs-mode and vi-ins-mode to reset codes
+bind "set emacs-mode-string \"\1\e[1m\2\""
+bind "set vi-ins-mode-string \"\1\e[1m\2\""
 
-  # Set vi-cmd-mode string to reverse mode
-  bind "set vi-cmd-mode-string \"\1\e[0m\2\""
+# Set vi-cmd-mode string to reverse mode
+bind "set vi-cmd-mode-string \"\1\e[0m\2\""
 
-  # Rebuild prompt command with exit status and history commands
-  eval 'IFS=";" read -ra parts <<< "$PROMPT_COMMAND"'
-  PROMPT_COMMAND=""
-  for part in "${parts[@]}"; do
-    [[ -z "$part" || "$part" == "history "* || "$part" == "(( \$? )) && "* || "$part" == ":" ]] && continue
-    PROMPT_COMMAND="$PROMPT_COMMAND;$part"
-  done
+# Rebuild prompt command with exit status and history commands
+eval 'IFS=";" read -ra parts <<< "$PROMPT_COMMAND"'
+PROMPT_COMMAND=""
+for part in "${parts[@]}"; do
+  [[ -z "$part" || "$part" == "history "* || "$part" == "(( \$? )) && "* || "$part" == ":" ]] && continue
+  PROMPT_COMMAND="$PROMPT_COMMAND;$part"
+done
 
-  # Do not do history-related things if using BLE
-  [ -z "${BLE_VERSION-}" ] && PROMPT_COMMAND="$PROMPT_COMMAND;history -a"
+# Do not do history-related things if using BLE
+[ -z "${BLE_VERSION-}" ] && PROMPT_COMMAND="$PROMPT_COMMAND;history -a"
 
-  # Set the exit status of the previous command for the prompt
-  PROMPT_COMMAND="(( \$? )) && __prompt_color=$'\e[91m' || __prompt_color=$'\e[92m'$PROMPT_COMMAND"
+# Set the exit status of the previous command for the prompt
+PROMPT_COMMAND="(( \$? )) && __prompt_color=$'\e[91m' || __prompt_color=$'\e[92m'$PROMPT_COMMAND"
 
-  unset parts part
+unset parts part
 
-  # May be needed for OpenBSD
-  # GIT_PS1_COLOR_PRE="\["
-  # GIT_PS1_COLOR_POST="\]"
+# May be needed for OpenBSD
+# GIT_PS1_COLOR_PRE="\["
+# GIT_PS1_COLOR_POST="\]"
 
-  # Set the prompt
-  [[ "$CHEZMOI_SUBSHELL" == 1 ]] && __subshell=" \[\e[1;95m\]{C}\[\e[22;39m\]"
-  __promptchar="❱"
-  __nl='\n'
-  (( ${COLUMNS:-80} > 120 )) && unset __nl
-  (( "$EUID" == 0 )) && __promptchar="󰄾"
-  [[ "$TERM" == vt220 ]] && { unset __gitglyph ; __promptchar='>' ; (( $EUID == 0 )) && __promptchar='#' ; }
-  PS1="[\[\e[96m\]\u\[\e[39m\]@\[\e[92m\]\h\[\e[39m\] \[\e[94m\]\$(__prompt_trim_pwd "\W")\[\e[39m\]]\[\e[22;24;27;49m\]${__subshell}\$(__git_ps1 ' (\[\e[1;${__orange}m\]${__gitglyph}\[\e[1;39m\]%s\[\e[22m\])' 2>/dev/null) ${__nl}\[\${__prompt_color}\]${__promptchar}\[\e[39m\] \[\e[0m\]"
-  unset __gitglyph
+# Set the prompt
+[[ "$CHEZMOI_SUBSHELL" == 1 ]] && __subshell=" \[\e[1;95m\]{C}\[\e[22;39m\]"
+__promptchar="❱"
+__nl='\n'
+(( ${COLUMNS:-80} > 120 )) && unset __nl
+(( "$EUID" == 0 )) && __promptchar="󰄾"
+[[ "$TERM" == vt220 ]] && { unset __gitglyph ; __promptchar='>' ; (( $EUID == 0 )) && __promptchar='#' ; }
+PS1="[\[\e[96m\]\u\[\e[39m\]@\[\e[92m\]\h\[\e[39m\] \[\e[94m\]\$(__prompt_trim_pwd "\W")\[\e[39m\]]\[\e[22;24;27;49m\]${__subshell}\$(__git_ps1 ' (\[\e[1;${__orange}m\]${__gitglyph}\[\e[1;39m\]%s\[\e[22m\])' 2>/dev/null) ${__nl}\[\${__prompt_color}\]${__promptchar}\[\e[39m\] \[\e[0m\]"
+unset __gitglyph
 
-  # Set readline options
-  bind 'set completion-ignore-case on'     # ignore case
-  bind 'set completion-map-case on'        # treat hyphens and underscores the same
-  #bind 'set show-all-if-ambiguous on'      # show all completions on first tab
-  bind 'set show-all-if-unmodified on'     # show all completions on first tab with no partial match
-  bind 'set colored-stats on'              # types in ls-style colors
-  bind 'set colored-completion-prefix on'  # display common prefix in ls-style colors
-  bind 'set mark-symlinked-directories on' # show directory symlinks with trailing slash
-  bind 'set visible-stats on'              # append character indicating type
-else
-  # Set up a basic prompt
-  unset __subshell
-  [[ "$CHEZMOI_SUBSHELL" == 1 ]] && __subshell=" {C}"
-  [[ "$TERM" == vt220 ]] && { unset __gitglyph ; __promptchar='$' ; (( $EUID == 0 )) && __promptchar='#' ; }
-  PS1="[\u@\h \$(__prompt_trim_pwd '\W')]\${__subshell}\$(__git_ps1 ' (${__gitglyph}%s)' 2>/dev/null) ${__promptchar} "
-fi
+# Set readline options
+bind 'set completion-ignore-case on'     # ignore case
+bind 'set completion-map-case on'        # treat hyphens and underscores the same
+#bind 'set show-all-if-ambiguous on'      # show all completions on first tab
+bind 'set show-all-if-unmodified on'     # show all completions on first tab with no partial match
+bind 'set colored-stats on'              # types in ls-style colors
+bind 'set colored-completion-prefix on'  # display common prefix in ls-style colors
+bind 'set mark-symlinked-directories on' # show directory symlinks with trailing slash
+bind 'set visible-stats on'              # append character indicating type
 
 # Load fzf for command history for bash and zsh
 if cmdcheck fzf; then
