sudo/doas check

diff --git a/run_onchange_nvim_init_lua.sh.tmpl b/run_onchange_nvim_init_lua.sh.tmpl
--- a/run_onchange_nvim_init_lua.sh.tmpl
+++ b/run_onchange_nvim_init_lua.sh.tmpl
@@ -5,6 +5,10 @@
 # .config/nvim/init.lua: {{ include "dot_config/nvim/init.lua" | sha256sum }}
 
 command -v nvim > /dev/null 2>&1 || exit 0
+if ! command -v sudo > /dev/null 2>&1 && ! command -v doas > /dev/null 2>&1; then
+  echo "Error: Cannot find sudo or doas" >&2
+  exit 1
+fi
 
 echo "Processing Run OnChange for nvim init.lua"
 
diff --git a/run_onchange_vimrc.sh.tmpl b/run_onchange_vimrc.sh.tmpl
--- a/run_onchange_vimrc.sh.tmpl
+++ b/run_onchange_vimrc.sh.tmpl
@@ -5,6 +5,10 @@
 # .config/vim/vimrc: {{ include "dot_config/vim/vimrc" | sha256sum }}
 
 command -v vim > /dev/null 2>&1 || exit 0
+if ! command -v sudo > /dev/null 2>&1 && ! command -v doas > /dev/null 2>&1; then
+  echo "Error: Cannot find sudo or doas" >&2
+  exit 1
+fi
 
 echo "Processing Run OnChange for vimrc"
 
