use flag files to indicate that something was done

diff --git a/run_once_after_system_setup.sh.tmpl b/run_once_after_system_setup.sh.tmpl
--- a/run_once_after_system_setup.sh.tmpl
+++ b/run_once_after_system_setup.sh.tmpl
@@ -17,6 +17,13 @@ trap 'exit 1' INT TERM
 groups=$(groups $LOGNAME)
 groups=${groups#$LOGNAME : }
 
+makeflag() {
+  { [ -z "$1" ] || [ "$1" != "${1%/*}" ] } && return
+
+  mkdir -p "$HOME"/.local/state/chezmoi/done
+  touch "$HOME"/.local/state/chezmoi/done/"$1"
+}
+
 # Add user to needed groups
 for group in video render input wheel; do
   # Skip groups from the list that do not exist
@@ -26,54 +33,36 @@ for group in video render input wheel; do
   # Add user to group (ok if already a member)
   echo "Adding $LOGNAME to $group"
   sudo usermod -aG "$group" "$LOGNAME"
-  if (( $? != 0 )); then
+  if [ $? -ne 0 ]; then
     echo "Error: Could not add $LOGNAME to $group" >&2
     exit 1
   fi
 done
 
 # Setup vi command
-if [[ ( ! -e /usr/bin/vi || -L /usr/bin/vi ) && -e $HOME/.local/bin/vi ]]; then
+if { [ ! -e /usr/bin/vi ] || [ -L /usr/bin/vi ] } && [ -e $HOME/.local/bin/vi ]; then
   echo "Installing vi script that encourages use of sudoedit"
   rm -f /usr/bin/vi &> /dev/null
   sudo install -o root -g root -m 755 "$HOME"/.local/bin/vi /usr/bin/vi
-  if (( $? != 0 )); then
+  if [ $? -ne 0 ]; then
     echo "Error: Could not install vi script to /usr/bin/vi" >&2
     exit 1
   fi
 fi
 
 # Fix $LOGNAME $HOME permissions
-unset list
-if command -v fd > /dev/null 2>&1; then
-  if [ -n "$(fd --hidden --no-ignore --exclude ".snapshots" --owner '!'"$LOGNAME" --max-results 1 . "$HOME")" ]; then
-    echo "Fixing $HOME permissions"
-    fd --hidden --no-ignore --exclude ".snapshots" --owner '!'"$LOGNAME" --print0 . "$HOME" | \
-      xargs -0 -r chown "$LOGNAME"
-  fi
-elif command -v fdfind > /dev/null 2>&1; then
-  if [ -n "$(fdfind --hidden --no-ignore --exclude ".snapshots" --owner '!'"$LOGNAME" --max-results 1 . "$HOME")" ]; then
-    echo "Fixing $HOME permissions"
-    fdfind --hidden --no-ignore --exclude ".snapshots" --owner '!'"$LOGNAME" --print0 . "$HOME" | \
-      xargs -0 -r chown "$LOGNAME"
-  fi
-else
-  if [ -n "$(find "$HOME" -name ".snapshots" -prune -or -not -user "$LOGNAME" -print -quit)" ]; then
-    echo "Fixing $HOME permissions"
-    find "$HOME" -name ".snapshots" -prune -or -not -user "$LOGNAME" -print0 | \
-      xargs -0 -r chown "$LOGNAME"
-  fi
+if [ ! -r "$HOME"/.local/state/chezmoi/done/home_permissions ]; then
+  sudo chown -R "$LOGNAME":"$(id -gn)" "$HOME"
 fi
-
-# Use setfacl to make sure $LOGNAME has permissions on files in $HOME
-if ! getfacl --omit-header "$HOME" 2> /dev/null | grep -q "^default:user:$LOGNAME:rwx"; then
-    echo "Setting ACLs on $HOME"
-    setfacl -R -m "u:$LOGNAME:rwX,d:u:$LOGNAME:rwX" -- "$HOME" 2> /dev/null
-fi
+# Unconditionally mark that this was done so it does not break permissions later
+makeflag home_permissions
 
 # Enable services: ssh-agent
 if command -v systemctl > /dev/null 2>&1; then
-  command -v ssh-agent > /dev/null 2>&1 && systemctl --user enable ssh-agent.service
+  if [ ! -r "$HOME"/.local/state/chezmoi/done/enable_sshd ]; then
+    command -v ssh-agent > /dev/null 2>&1 && systemctl --user enable ssh-agent.service
+    [ $? -eq 0 ] && makeflag enable_sshd
+  fi
 fi
 
 # Set up $LOGNAME crontab
@@ -98,13 +87,13 @@ if command -v crontab > /dev/null 2>&1; then
   new_cron_lines=()
   for var in "${crontab_vars[@]}"; do
     ref="crontab_$var"
-    [[ -z "$var" || -z "${!ref}" ]] && continue
+    { [ -z "$var" ] || [ -z "${!ref}" ] } && continue
 
     echo "$existing_crontab" | grep -qE "^$var *=" && continue
     echo "Adding $var variable to crontab"
     new_cron_lines+=("$var = ${!ref}")
   done
-  if (( ${#new_cron_lines[@]} > 0 )); then
+  if [ ${#new_cron_lines[@]} -gt 0 ]; then
     {
       printf '%s\n' "${new_cron_lines[@]}"
       crontab -l 2> /dev/null
@@ -113,13 +102,16 @@ if command -v crontab > /dev/null 2>&1; then
 fi
 
 # Enable and start cronie.service
-if ! systemctl is-enabled -q cronie.service; then
-  sudo systemctl enable --now cronie.service
+if [ ! -r "$HOME"/.local/state/chezmoi/done/enable_cronie ]; then
+  if ! systemctl is-enabled -q cronie.service; then
+    sudo systemctl enable --now cronie.service
+    [ $? -eq 0 ] && makeflag enable_cronie
+  fi
 fi
 
 {{- if $is_desktop }}
 # Set up DMS Idle Inhibitor Handler in cron
-if command -v crontab > /dev/null 2>&1 && [[ -e "$HOME"/.local/bin/handle_dms_idle_inhibitor.sh ]] && \
+if command -v crontab > /dev/null 2>&1 && [ -e "$HOME"/.local/bin/handle_dms_idle_inhibitor.sh ] && \
    ! crontab -l 2> /dev/null | grep -qF 'handle_dms_idle_inhibitor.sh'; then
   echo "Adding DMS Idle Inhibitor Handler to $LOGNAME crontab"
   {
@@ -129,49 +121,58 @@ if command -v crontab > /dev/null 2>&1 && [[ -e "$HOME"/.local/bin/handle_dms_id
 fi
 
 # Setup dms-greeter
-if [ -e /etc/greetd/config.toml ]; then
-  if ! grep -qE "^\s*command\s*=.*dms-greeter" /etc/greetd/config.toml; then
-    if ! grep -q "^\[default_session\]" /etc/greetd/config.toml; then
-      echo "Error: greetd config missing default_session section" >&2
-    else
-      echo "Setting up greetd to use dms-greeter with niri"
-      # Comment out any lines with command = 
-      sudo sed -ri 's/^(\s*)(command.*)$/\1# \2/' /etc/greetd/config.toml
-      # Under the default_session section heading, add a dms-greeter line
-      sudo sed -ri 's#^(\[default_session].*)$#\1\r\ncommand = "/usr/bin/dms-greeter --no-save-username --command niri"#' /etc/greetd/config.toml
-      # Enable the service
-      sudo systemctl enable greetd
-    fi
-  fi
-
-  if getent group greeter > /dev/null 2>&1 && ! groups | sed "s/^$LOGNAME : //" | grep -qw greeter; then
-    echo "Adding $LOGNAME to $group"
-    sudo usermod -aG greeter "$LOGNAME"
-  fi
-
-  if [[ -n "$(find /var/cache/dms-greeter -maxdepth 0 -mindepth 0 -not -group greeter -type d)" ]]; then
-    echo "Fixing permissions on /var/cache/dms-greeter"
-    sudo chgrp greeter /var/cache/dms-greeter
-  fi
-
-  # Install dms-greeter settings/colors
-  for file in settings colors; do
-    if [ -r "$HOME"/.config/niri/greeter/"$file".json ]; then
-      if [ -r /var/cache/dms-greeter/"$file".json ]; then
-        : # do nothing
-      elif [ ! -x /var/cache/dms-greeter ] || ! sudo test -r /var/cache/dms-greeter/"$file".json; then
-        echo "Configuring dms-greeter $file"
-        sudo install -m 644 -o root -g "$(id -gn root)" \
-          "$HOME"/.config/niri/greeter/"$file".json /var/cache/dms-greeter
+if [ ! -r "$HOME"/.local/state/chezmoi/done/configure_greetd ]; then
+  if [ -e /etc/greetd/config.toml ]; then
+    if ! grep -qE "^\s*command\s*=.*dms-greeter" /etc/greetd/config.toml; then
+      if ! grep -q "^\[default_session\]" /etc/greetd/config.toml; then
+        echo "Error: greetd config missing default_session section" >&2
+      else
+        echo "Setting up greetd to use dms-greeter with niri"
+        # Comment out any lines with command = 
+        sudo sed -ri 's/^(\s*)(command.*)$/\1# \2/' /etc/greetd/config.toml
+        # Under the default_session section heading, add a dms-greeter line
+        sudo sed -ri 's#^(\[default_session].*)$#\1\r\ncommand = "/usr/bin/dms-greeter --no-save-username --command niri"#' /etc/greetd/config.toml
+        # Enable the service
+        sudo systemctl enable greetd
       fi
     fi
-  done
+
+    if getent group greeter > /dev/null 2>&1 && ! groups | sed "s/^$LOGNAME : //" | grep -qw greeter; then
+      echo "Adding $LOGNAME to $group"
+      sudo usermod -aG greeter "$LOGNAME"
+    fi
+
+    if [[ -n "$(find /var/cache/dms-greeter -maxdepth 0 -mindepth 0 -not -group greeter -type d)" ]]; then
+      echo "Fixing permissions on /var/cache/dms-greeter"
+      sudo chgrp greeter /var/cache/dms-greeter
+    fi
+
+    # Install dms-greeter settings/colors
+    for file in settings colors; do
+      if [ -r "$HOME"/.config/niri/greeter/"$file".json ]; then
+        if [ -r /var/cache/dms-greeter/"$file".json ]; then
+          : # do nothing
+        elif [ ! -x /var/cache/dms-greeter ] || ! sudo test -r /var/cache/dms-greeter/"$file".json; then
+          echo "Configuring dms-greeter $file"
+          sudo install -m 644 -o root -g "$(id -gn root)" \
+            "$HOME"/.config/niri/greeter/"$file".json /var/cache/dms-greeter
+        fi
+      fi
+    done
+  fi
+  makeflag configure_greetd
 fi
 
 # Enable services: DMS and ydotool
 if command -v systemctl > /dev/null 2>&1; then
-  command -v dms > /dev/null 2>&1 && systemctl --user enable dms.service
-  command -v ydotool > /dev/null 2>&1 && systemctl --user enable ydotool.service
+  if [ ! -r "$HOME"/.local/state/chezmoi/done/enable_dms ]; then
+    command -v dms > /dev/null 2>&1 && systemctl --user enable dms.service
+    [ $? -eq 0 ] && makeflag enable_dms
+  fi
+  if [ ! -r "$HOME"/.local/state/chezmoi/done/enable_ydotool ]; then
+    command -v ydotool > /dev/null 2>&1 && systemctl --user enable ydotool.service
+    [ $? -eq 0 ] && makeflag enable_ydotool
+  fi
 fi
 {{- end }}
 
