test

diff --git a/run_once_after_system_setup.sh.tmpl b/run_once_after_system_setup.sh.tmpl
--- a/run_once_after_system_setup.sh.tmpl
+++ b/run_once_after_system_setup.sh.tmpl
@@ -9,7 +9,7 @@
 {{- $is_trusted := has .chezmoi.hostname $trusted_hosts -}}
 
 if ! command -v sudo > /dev/null 2>&1 && ! command -v doas > /dev/null 2>&1; then
-  echo "Error: Cannot find sudo or doas" >&2
+  echo "Warning: Cannot find sudo or doas" >&2
   exit 0
 fi
 
