Add system_setup.sh Update pkg_install.sh

diff --git a/run_once_before_pkg_install.sh.tmpl b/run_once_before_pkg_install.sh.tmpl
--- a/run_once_before_pkg_install.sh.tmpl
+++ b/run_once_before_pkg_install.sh.tmpl
@@ -18,8 +18,8 @@ if [[ "$ID" =~ ^(arch|artix|cachyos|garuda|endeavouros|manjaro)$ || " $ID_LIKE "
   # Go through the package list and find packages that are not installed
   need=()
   packages=(
-    base-devel git openssh neovim vim man-db apparmor firejail rsync ripgrep fd
-    networkmanager openresolv htop btop jq 7zip
+    base-devel git openssh neovim vim man-db apparmor firejail rsync
+    networkmanager openresolv htop btop jq 7zip bat ripgrep fd
   )
   {{- if $is_desktop }}
   packages+=(
@@ -32,7 +32,7 @@ if [[ "$ID" =~ ^(arch|artix|cachyos|garuda|endeavouros|manjaro)$ || " $ID_LIKE "
     ttf-nerd-fonts-symbols ttf-nerd-fonts-symbols-common ttf-nerd-fonts-symbols-mono
     imv imagemagick python-pillow python-cairocffi
     nwg-look adw-gtk-theme breeze-gtk breeze-icons
-    nm-connection-editor yad galculator nautilus gvfs-dnssd librewolf-bin
+    nm-connection-editor yad mpv geany galculator nautilus gvfs-dnssd librewolf-bin
   )
   {{- end }}
 
@@ -52,32 +52,50 @@ if [[ "$ID" =~ ^(arch|artix|cachyos|garuda|endeavouros|manjaro)$ || " $ID_LIKE "
   # Install missing packages
   if (( ${#need[@]} > 0 )); then
     echo "Installing packages: ${need[@]}"
-    sudo pacman -Syu --needed --noconfirm "${need[@]}"
+    sudo pacman -Syu --disable-download-timeout --needed --noconfirm "${need[@]}"
+    ret=$?
+    if [ $ret -ne 0 ]; then
+      echo "Error: pacman exited with error code $ret" >&2
+      exit 1
+    fi
   fi
+else
+  echo "Error: Unsupported OS (${ID:-Could not determine OS})" >&2
+  exit 1
+fi
 
-  # Setup vi command
-  if [[ ( ! -e /usr/bin/vi || -L /usr/bin/vi ) && -e $HOME/.local/bin/vi ]]; then
-    echo "Installing vi script that encourages use of sudoedit"
-    rm -f /usr/bin/vi &> /dev/null
-    sudo install -o root -g root -m 755 "$HOME"/.local/bin/vi /usr/bin/vi
+# Setup vi command
+if [[ ( ! -e /usr/bin/vi || -L /usr/bin/vi ) && -e $HOME/.local/bin/vi ]]; then
+  echo "Installing vi script that encourages use of sudoedit"
+  rm -f /usr/bin/vi &> /dev/null
+  sudo install -o root -g root -m 755 "$HOME"/.local/bin/vi /usr/bin/vi
+  if [ $? -ne 0 ]; then
+    echo "Error: Could not install vi script to /usr/bin/vi" >&2
+    exit 1
   fi
+fi
 
-  groups=$(groups $LOGNAME)
-  groups=${groups#$LOGNAME : }
+groups=$(groups $LOGNAME)
+groups=${groups#$LOGNAME : }
 
-  # Add user to needed groups
-  for group in video render input wheel; do
-    # Skip groups from the list that do not exist
-    getent group "$group" &> /dev/null || continue
-    # Skip groups already a member of
-    echo "$groups" | grep -qw "$group" && continue
-    # Add user to group (ok if already a member)
-    echo "Adding $LOGNAME to $group"
-    sudo usermod -aG "$group" "$LOGNAME"
-  done
+# Add user to needed groups
+for group in video render input wheel; do
+  # Skip groups from the list that do not exist
+  getent group "$group" &> /dev/null || continue
+  # Skip groups already a member of
+  echo "$groups" | grep -qw "$group" && continue
+  # Add user to group (ok if already a member)
+  echo "Adding $LOGNAME to $group"
+  sudo usermod -aG "$group" "$LOGNAME"
+  if [ $? -ne 0 ]; then
+    echo "Error: Could not add $LOGNAME to $group" >&2
+    exit 1
+  fi
+done
 
-  {{- if $is_desktop }}
-  # Setup dms-greeter
+{{- if $is_desktop }}
+# Setup dms-greeter
+if [ -e /etc/greetd/config.toml ]; then
   if ! grep -qE "^\s*command\s*=.*dms-greeter" /etc/greetd/config.toml; then
     if ! grep -q "^\[default_session\]" /etc/greetd/config.toml; then
       echo "Error: greetd config missing default_session section" >&2
@@ -91,12 +109,17 @@ if [[ "$ID" =~ ^(arch|artix|cachyos|garuda|endeavouros|manjaro)$ || " $ID_LIKE "
       sudo systemctl enable greetd
     fi
   fi
-
-  # Enable services: DMS and ydotool
-  systemctl --user enable dms.service ssh-agent.service ydotool.service
-  {{- end }}
-else
-  echo "Error: Unsupported OS (${ID:-Could not determine OS})" >&2
-  exit 1
+  if getent group greeter > /dev/null 2>&1 && ! groups | sed "s/^$LOGNAME : //" | grep -qw greeter; then
+    echo "Adding $LOGNAME to $group"
+    sudo usermod -aG greeter "$LOGNAME"
+  fi
 fi
+
+if command -v systemctl > /dev/null 2>&1; then
+  # Enable services: DMS and ydotool
+  command -v dms > /dev/null 2>&1 && systemctl --user enable dms.service
+  command -v ssh-agent > /dev/null 2>&1 && systemctl --user enable ssh-agent.service
+  command -v ydotool > /dev/null 2>&1 && systemctl --user enable ydotool.service
+fi
+{{- end }}
 
