no exit 1s

diff --git a/run_onchange_ssh_host_keys.sh.tmpl b/run_onchange_ssh_host_keys.sh.tmpl
--- a/run_onchange_ssh_host_keys.sh.tmpl
+++ b/run_onchange_ssh_host_keys.sh.tmpl
@@ -6,7 +6,7 @@
 
 if ! command -v sudo > /dev/null 2>&1 && ! command -v doas > /dev/null 2>&1; then
   echo "Error: Cannot find sudo or doas" >&2
-  exit 1
+  exit 0
 fi
 
 sudo=doas
@@ -15,7 +15,7 @@ command -v sudo > /dev/null 2>&1 && sudo=sudo
 echo "Processing Run OnChange for SSH Host Keys"
 
 hostname=$(hostname 2> /dev/null || hostnamectl hostname 2> /dev/null)
-[ -z "$hostname" ] && { echo "Error: Could not determine hostname" >&2 ; exit 1 ; }
+[ -z "$hostname" ] && { echo "Error: Could not determine hostname" >&2 ; exit 0 ; }
 hostname=${hostname%%.*}
 
 # Copy home_known_hosts to /etc/ssh/ssh_known_hosts if they differ
@@ -42,7 +42,7 @@ if [ "$defined_pub_key" != "$system_key" ]; then
   updated_key=$(pass show systems/"$hostname"/ssh_host_ed25519_key 2> /dev/null)
   if [ -z "$update_key" ]; then
     echo "Could not read ssh key from password store" >&2
-    exit 1
+    exit 0
   fi
 
   echo "Updating system ssh_host_ed25519_key"
