Make much more robust

diff --git a/srv/scripts/bin/g b/srv/scripts/bin/g
--- a/srv/scripts/bin/g
+++ b/srv/scripts/bin/g
@@ -7,6 +7,9 @@ case $progname in
   ga)
     action=add
     ;;
+  gss)
+    action=status
+    ;;
   gp)
     action=push
     ;;
@@ -24,7 +27,23 @@ usage() {
   elif [ $action = push ] || [ $action = diff ]; then
     echo "usage: $progname [-h] [-C dir] [..]"
   else
-    echo "usage: $progname [-h] [-C dir] [-S|--skip-ci] [--allow-empty] --allow-empty-message|COMMIT MESSAGE"
+    echo "usage: $progname [options]"
+    echo "Options:"
+    echo "-h, --help             : this help text"
+    echo "-t, --test             : test mode"
+    echo "-C, --changedir PATH   : Run as if git was started in PATH instead of the current directory"
+    echo "-a, --all              : automatically stage modified/deleted files (new files must be added like git commit)"
+    echo "-A, --add PATH         : run 'git add' on specified PATH before commit (can be used more than once)"
+    echo "-p, --path PATH        : commit specific paths instead of --all (can be used more than once)"
+    echo "-P, --print-latest-tag : print latest version tag for repo"
+    echo "-L, --latest-tag       : update latest version tag for commit (overrides -t/--tag)"
+    echo "-F, --tag-from-file    : get the tag from CONTAINER_VERSION in Dockerfile for commit (overrides -t/--tag)"
+    echo "-T, --tag TAG          : save or update tag for commit"
+    echo "-S, --skip-ci          : add [skip ci] tag to commit message"
+    echo "--allow-empty          : Allow commit without any changed files"
+    echo "--allow-empty-message  : Allow empty commit message"
+    echo
+    echo "COMMIT MESSAGE         : Free form text for commit message (may need quoting in some cases)"
     echo "For 'COMMIT MESSAGE' to contain new lines, use '\n'"
     echo "If passing 'COMMIT MESSAGE without quotes, use '\\\n'"
   fi
@@ -33,24 +52,83 @@ usage() {
 
 shopt -s extglob
 
-unset dir allow_empty
+unset dir latest_tag
 test_mode=false
+allow_empty=false
 allow_empty_message=false
 skip_ci=false
+all=true
+all_set=false
+add_paths=()
+commit_paths=()
+print_latest_tag=false
+use_latest_tag=false
+use_dockerfile_for_tag=false
 while [[ $# -gt 0 ]]; do
   case "$1" in
     -t|--test) test_mode=true ; shift ;;
-    -C) [[ -z "$2" || $2 =~ ^- ]] && shift && echo "Error: Missing argument" && usage 1; dir=$2 ; shift 2 ;;
+    -C|--changedir)
+      [[ -z "$2" || $2 =~ ^- ]] && shift && echo "Error: Missing argument" && usage 1; dir=$2 ; shift 2 ;;
+    -a|--all) all_set=true ; all=true ; shift ;;
+    -A|--add)
+      if [[ -z "$2" || $2 =~ ^- ]]; then
+        shift
+        echo "Error: Missing argument"
+        usage 1
+      else
+        add_paths+=("$2")
+        shift 2
+      fi ;;
+    -p|--path)
+      if [[ -z "$2" || $2 =~ ^- ]]; then
+        shift
+        echo "Error: Missing argument"
+        usage 1
+      else
+        commit_paths+=("$2")
+        shift 2
+        all=false
+      fi ;;
+    -P|--print-latest-tag) print_latest_tag=true ; shift ;;
+    -L|--latest-tag) use_latest_tag=true ; shift ;;
+    -F|--tag-from-file) use_dockerfile_for_tag=true ; shift ;;
+    -T|--tag)
+      [[ -z "$2" || $2 =~ ^- ]] && shift && echo "Error: Missing argument" && usage 1; tag=$2 ; shift 2 ;;
     -S|--skip-ci) skip_ci=true ; shift ;;
-    --allow-empty) allow_empty="--allow-empty" ; shift ;;
+    --allow-empty) allow_empty=true ; all=false ; shift ;;
     --allow-empty-message) allow_empty_message=true ; shift ;;
     -h|--help) usage ;;
     *) break ;;
   esac
 done
 
-[ -z "$1" ] && ! $allow_empty_message && [ $action != push ] && [ $action != diff ] && usage
+if [ $action = commit ] && $all_set && [ ${#commit_paths[@]} -gt 0 ]; then
+  echo "Error: Cannot use -a/--all with -p/--path" > /dev/stderr
+  exit 1
+fi
 
+if $print_latest_tag || $use_latest_tag; then
+  latest_tag=$(git ${dir:+-C $dir }tag | sort -Vr | head -n1)
+  if [ -z "$latest_tag" ]; then
+    echo "Error: Could not determine latest tag" > /dev/stderr
+    exit 1
+  fi
+  if $print_latest_tag; then
+    echo "Latest tag = '$latest_tag'"
+    exit 0
+  fi
+fi
+
+if $use_dockerfile_for_tag; then
+  dockerfile_tag=$(awk -F= '/^ARG CONTAINER_VERSION=/{print $2;exit}' ${dir:+$dir/}Dockerfile)
+  [ -n "$dockerfile_tag" ] && latest_tag=$dockerfile_tag
+fi
+
+[ -z "$1" ] && ! $allow_empty_message && [[ ! $action =~ ^(push|diff|status)$ ]] && usage
+
+# Set tag to latest tag or $tag if unset
+tag=${latest_tag:-$tag}
+tag=${tag/#+(v)/}
 commitmsg=$(echo "$@")
 $skip_ci && commitmsg="$commitmsg [skip ci]"
 
@@ -61,6 +139,8 @@ if $test_mode; then
     for f in "${args[@]:1}"; do
       echo " - $f"
     done
+  elif [ $action = status ]; then
+    echo "Running 'git status'"
   elif [ $action = push ]; then
     echo "Running 'git push'"
     echo "Additional args: '$@'"
@@ -68,8 +148,18 @@ if $test_mode; then
     echo "Running 'git diff'"
     echo "Additional args: '$@'"
   else
-    echo "Running 'git commit -a' and 'git push'"
-    [ -n "$allow_empty" ] && echo "Empty commits allowed"
+    if [ ${#add_paths[@]} -gt 0 ]; then
+      echo "Running 'git add ${add_paths[@]}"
+    fi
+    if [ -n "$tag" ]; then
+      echo "Adding tag v$tag to commit"
+    fi
+    if $all; then
+      echo "Running 'git commit -a' and 'git push'${tag:+ (with tag options)}"
+    else
+      echo "Running 'git commit ${commit_paths[@]}' and 'git push'${tag:+ (with tag options)}"
+    fi
+    $allow_empty && echo "Empty commits allowed"
     $allow_empty_message && echo "Empty commit messages allowed"
     echo "commit message = '$commitmsg'"
   fi
@@ -79,15 +169,28 @@ fi
 
 if [ $action = add ]; then
   git ${dir:+-C $dir }add "$@"
+elif [ $action = status ]; then
+  git ${dir:+-C $dir }status
 elif [ $action = push ]; then
   git ${dir:+-C $dir }push "$@"
 elif [ $action = diff ]; then
   git ${dir:+-C $dir }diff "$@"
 else
-  if $allow_empty_message && [ -z "$commitmsg" ]; then
-    git ${dir:+-C $dir }commit -a --allow-empty-message
-  else
-    git ${dir:+-C $dir }commit -a -m "$(printf "$commitmsg")"
+  if [ ${#add_paths[@]} -gt 0 ]; then
+    git ${dir:+-C $dir }add "${add_paths[@]}"
   fi
-  git ${dir:+-C $dir }push
+  ! $all_set && $allow_empty && [ ${#commit_paths[@]} -eq 0 ] && commit_paths=("--allow-empty")
+  [[ $all == true || ${#commit_paths[@]} -eq 0 ]] && commit_paths=("--all")
+  if $allow_empty_message && [ -z "$commitmsg" ]; then
+    git ${dir:+-C $dir }commit "${commit_paths[@]}" --allow-empty-message
+  else
+    git ${dir:+-C $dir }commit "${commit_paths[@]}" -m "$(printf "$commitmsg")"
+  fi
+  if [ -n "$tag" ]; then
+    git ${dir:+-C $dir }tag -f -a "v$tag" -m "v$tag"
+    git ${dir:+-C $dir }push origin HEAD
+    git ${dir:+-C $dir }push -f origin "v$tag"
+  else
+    git ${dir:+-C $dir }push
+  fi
 fi
