Make sure required programs are installed

diff --git a/dot_local/bin/executable_vm b/dot_local/bin/executable_vm
--- a/dot_local/bin/executable_vm
+++ b/dot_local/bin/executable_vm
@@ -15,6 +15,8 @@ clone_usage() {
 }
 
 clone() {
+  command -v virt-clone &>/dev/null || { echo "Error: virt-clone is required for this program" >&2 ; exit 1 ; }
+
   local connect=(--connect qemu:///system) start=false opts=()
   local OPTIND=1 OPTARG="" opt=""
   while getopts ":huc:sS" opt; do
@@ -56,6 +58,8 @@ create_usage() {
 }
 
 create() {
+  command -v virt-install &>/dev/null || { echo "Error: virt-install is required for this program" >&2 ; exit 1 ; }
+
   local vm_name=$1 vm_ram=8192 vm_vcpus=2 vm_disk=20 vm_iso="" iso_path=/share/software/Isos
 
   # shellcheck disable=1091
@@ -503,6 +507,8 @@ stop() {
 }
 
 get_os_variant() {
+  command -v virt-install &>/dev/null || { echo "Error: virt-install is required for this program" >&2 ; exit 1 ; }
+
   (( $# < 1 )) && { echo "usage: get_os_variant SEARCHSTRING" ; return 1 ; }
   virt-install --osinfo list | \
     awk -F, -v os="$1" '$0 ~ "^" os "([[:digit:]]|$)" { print $1 }' | \
@@ -512,12 +518,13 @@ get_os_variant() {
 
 get_iso() {
   (( $# < 1 )) && { echo "usage: get_iso ISOSEARCH [VM_ISO]" ; return 1 ; }
-  local iso_search=$1 vm_iso=$2
+  local iso_search=$1 vm_iso=$2 ng=false
   if [[ -z "$vm_iso" ]]; then
-    shopt -u nullglob
+    shopt -q ng && ng=true ; shopt -u nullglob
     for iso in "$iso_path"/$iso_search; do
       vm_iso=$(printf "%s\n%s\n" "$vm_iso" "$iso" | grep . | sort -V | tail -n1)
     done
+    $ng && shopt -s nullglob ; ng=false
   fi
   [[ -z "$vm_iso"   ]] && { echo "Error: ISO not defined" ; exit 1 ; }
   [[ ! -r "$vm_iso" ]] && { echo "Error: ISO not found"   ; exit 1 ; }
@@ -542,6 +549,9 @@ main_usage() {
 }
 
 main() {
+
+  command -v virsh &>/dev/null || { echo "Error: virsh is required for this program" >&2 ; exit 1 ; }
+
   case "$1" in
     clone|copy|duplicate|dupe) shift ; clone "$@" ;;
     create|new) shift ; create "$@" ;;
