Update .local/bin/vi

diff --git a/dot_local/bin/executable_vi b/dot_local/bin/executable_vi
--- a/dot_local/bin/executable_vi
+++ b/dot_local/bin/executable_vi
@@ -1,40 +1,48 @@
 #!/usr/bin/env bash
 
+# Find and set editor
+if vi_cmd=$(command -v nvim 2> /dev/null); then
+  EDITOR=$vi_cmd
+elif vi_cmd=$(command -v vim 2> /dev/null); then
+  EDITOR=$vi_cmd
+elif vi_cmd=$(command -v vi 2> /dev/null) && [[ "$(realpath "$0")" != "$vi_cmd" ]]; then
+  EDITOR=$vi_cmd
+else
+  echo "Error: Cannot find neovim or vim or other editor" >&2
+  exit 1
+fi
+
 if [[ -n "$SUDO_USER" ]] && [[ "$(ps -o comm= -p $PPID)" == "sudo" ]]; then
   echo "Use sudoedit" >&2
   exit 1
 else
   args=("$@")
-  if command -v chezmoi > /dev/null 2>&1 && [ -d "$HOME"/.local/share/chezmoi ]; then
+  if command -v chezmoi > /dev/null 2>&1 && [[ -d "$HOME"/.local/share/chezmoi ]]; then
     args=()
     chezmoi=()
+    editor=()
     mapfile -t chezmoi_managed < <(chezmoi managed -p absolute)
 
     # Look for chezmoi managed files and edit them with chezmoi edit instead of vi
     for arg in "$@"; do
-      if [[ -n "$arg" && " ${chezmoi_managed[*]} " == *" $(realpath "$arg" 2> /dev/null) "* ]]; then
+      if [[ " ${chezmoi_managed[*]} " == *" $(realpath "$arg" 2> /dev/null) "* ]]; then
         chezmoi+=("$arg")
-      else
+      elif echo "$arg" | grep -qEw -- "^-(o|O)"; then
         args+=("$arg")
+      else
+        editor+=("$arg")
       fi
     done
 
     if (( ${#chezmoi[@]} > 0 )); then
       echo "Using 'chezmoi edit' for: ${chezmoi[@]}"
-      chezmoi edit "${chezmoi[@]}"
+      chezmoi_editor=("$EDITOR" "${args[@]}")
+      EDITOR="${chezmoi_editor[@]}" chezmoi edit "${chezmoi[@]}"
     fi
   fi
 
   # Edit any other files with nvim or vim
-  if (( ${#args[@]} > 0 )); then
-    if command -v nvim &> /dev/null; then
-      # echo "Using 'nvim' for: ${args[@]}"
-      exec nvim "${args[@]}"
-    elif command -v vim &> /dev/null; then
-      # echo "Using 'vim' for: ${args[@]}"
-      exec vim "${args[@]}"
-    else
-      echo "Error: Cannot find neovim or vim" >&2
-    fi
+  if (( ${#editor[@]} > 0 )); then
+    exec "$EDITOR" "${args[@]}" "${editor[@]}"
   fi
 fi
