Update .local/bin/rbw-menu

diff --git a/dot_local/bin/executable_rbw-menu b/dot_local/bin/executable_rbw-menu
--- a/dot_local/bin/executable_rbw-menu
+++ b/dot_local/bin/executable_rbw-menu
@@ -9,6 +9,11 @@ if ! command -v rbw &>/dev/null; then
   exit 1
 fi
 
+if ! command -v jq &>/dev/null; then
+  echo OK | "${fuzzel[@]}" -p "Error: Can't find jq> "
+  exit 1
+fi
+
 if ! command -v wtype &>/dev/null && ! command -v ydotool &>/dev/null; then
   echo OK | "${fuzzel[@]}" -p "Error: Can't find wtype/ydotool> "
   exit 1
